# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 092ec20612ad51292e197e90b09a7bd8cb68ffb4149364e2d22e118df3a5266f4e72ff8c702fa0727f6750410644b8edc14ab3ac26bee5a9605ced8bef66a3f0

test:
  secret_key_base: fa7920a752cad4aa5490962bee4af358b16359cb37302781ab414ee263d897504a5e6003bc6576615097b6c2218da9eba442fb494e4ad58ce03cd18bb2694a09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
